version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    branches-ignore:
      -"main"
    validate:
      - do: approvals
        min:
          count: 1
        required:
          assignees: true
